# Generated by Django 4.2 on 2023-04-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='value_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='feature',
            name='value_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='feature',
            name='value_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Value'),
        ),
        migrations.AddField(
            model_name='featurename',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='featurename',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='featurename',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Text'),
        ),
    ]
