# Generated by Django 4.2 on 2023-04-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_category_en_and_more'),
        ('cart', '0002_rename_discout_price_cart_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='product_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('New', 'New'), ('In_progress', 'In progress'), ('Error', 'Error'), ('Completed', 'Completed')], default='In_progress', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ru',
            field=models.CharField(choices=[('New', 'New'), ('In_progress', 'In progress'), ('Error', 'Error'), ('Completed', 'Completed')], default='In_progress', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_uz',
            field=models.CharField(choices=[('New', 'New'), ('In_progress', 'In progress'), ('Error', 'Error'), ('Completed', 'Completed')], default='In_progress', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
