# Generated by Django 4.2 on 2023-04-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_product_en_cartitem_product_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_ru',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_uz',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_ru',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product_uz',
        ),
    ]
