# Generated by Django 4.2 on 2023-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_purchasedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedproduct',
            name='qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
